apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-proxy
  name: ms-proxy
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: ms-proxy
status:
  loadBalancer: {}
