apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-proxy
  name: ms-proxy
spec:
  type: LoadBalancer
  ports:
  - name: http
    nodePort: 30101
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 30102
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: ms-proxy
status:
  loadBalancer:
    ingress:
    - ip: 34.120.4.126
